### ISSUE TITLE
Missing :action key on routes definition, please check your routes (rails 5)

### ISSUE THREAD

**Issue by sudarshandhokale** [pragmaticly/mails_viewer#14]

**Comment by johnrails** [comment]
I'm having this issue too. We are trying to upgrade from Rails 4.2 to Rails 5.0. Any update on this?

**Comment by krisleech** [comment]
There is a PR here: https://github.com/pragmaticly/mails_viewer/pull/15

But there hasn't been any activity on this repo in years so I'm not sure it will get merged.

**Comment by sishen** [comment]
done.
